version: '3'

services:
  nifi:
#    image: apache/nifi:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./nifi-data:/opt/nifi/nifi-current/data
      - ./etl:/opt/nifi/nifi-current/etl
    environment:
      - NIFI_WEB_HTTP_PORT=8080
